### ISSUE TITLE
Not able to fetch IN & MI (Global) ROMs

### ISSUE THREAD

**Issue by techyminati** [YuKongA/Xiaomi-Update-Info#2]
* Hi, It's not able to fetch global roms, are the endpoints different? I have already tried modifying the payload headers. Thanks in advance.

**Comment by YuKongA** [comment]
I have basically given up on this project, you can use https://github.com/YuKongA/Updater, which has more complete support

**Comment by YuKongA** [comment]
> * Hi, It's not able to fetch global roms, are the endpoints different? I have already tried modifying the payload headers. Thanks in advance.

I have basically given up on this project, you can use https://github.com/YuKongA/Updater, which has more complete support

**Comment by techyminati** [comment]
@YuKongA sure but how can i fetch download links using your updater app?

**Comment by techyminati** [comment]
It just shows information about upcoming update.
